name: Deploy Dev Infrastructure

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      # Step 1: Apply remote-backend (S3 + DynamoDB)
      - name: Init remote-backend
        working-directory: ./remote-backend
        run: terraform init

      - name: Apply remote-backend (one-time setup)
        working-directory: ./remote-backend
        run: terraform apply -auto-approve

      # Step 2: Deploy dev infra
      - name: Init dev
        working-directory: ./dev
        run: terraform init

      - name: Apply dev
        working-directory: ./dev
        run: terraform apply -auto-approve
